setono_sylius_peak_admin_peak_index:
    path: /peak
    methods: [GET,POST]
    defaults:
        _controller: Setono\SyliusPeakPlugin\Controller\Admin\PeakController::index
        
setono_sylius_peak_admin_peak_register_webhooks:
    path: /peak/register-webhooks
    methods: [GET]
    defaults:
        _controller: Setono\SyliusPeakPlugin\Controller\Admin\PeakController::registerWebhooks
